name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '.github/*.yml'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        haxe:
          - latest
          - 4.3.5
          - 3.4.7
        include:
          - lib_hxml: lib.hxml
            haxe: 3.4.7
          - lib_hxml: lib_haxe3.hxml
            haxe: 3.4.7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Test NPM
        run: |
          npm ci
          npm run test

      - name: Install Haxe ${{ matrix.haxe }}
        uses: ./  
        with:
          haxe-version: ${{ matrix.haxe }}

      - name: Install Haxe ${{ matrix.haxe }} (Verification)
        uses: ./  
        with:
          haxe-version: ${{ matrix.haxe }}
          cache-dependency-path: 'test-workflow/${{ matrix.lib_hxml }}'

      - run: haxe -version

      - run: haxelib install test-workflow/${{ matrix.lib_hxml }} --always

      - name: Compile testing code
        run: |
          haxe \
            -cp test-workflow \
            -lib hxnodejs \
            -main Main \
            -js test-workflow.js
